version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-217-213-79.eu-west-1.compute.amazonaws.com
            database: dcjajmulesug3p
            user: lyfptvcamdxjjg
            password: 1fed72f9c5a6600e1ba8bcad6af98904fc0bda349e4e4bcc786c0b1a95060e28
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true